essential-packages:
  pkg.installed:
    - pkgs:
      - bash
      - besagent
      - llcertsso
      - encase
      - splunkforwarder
      - isecesp
      - isecespaac
      - isecespfileaccess
      - isecgrt
      - isecrt
      - isectp
      - maprovision
      - mfecma
      - mfert
      - vim-nox
      - zsh
      - ntp
      - curl
